#!/usr/bin/env bash
# Writes wwwroot/sitemap.xml from the showcase's routes: the first @page of every page (the others
# are aliases MudBlazor keeps for old links), without /not-found and the /iframe/ pages that
# examples embed. sync-mudblazor-docs.sh runs it after porting new pages; run it by hand after
# adding a page of the showcase's own.
#
#   samples/MudShadcn.Showcase/generate-sitemap.sh
#   SITE_URL=https://example.com samples/MudShadcn.Showcase/generate-sitemap.sh   # another origin
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SITE_URL="${SITE_URL:-https://mudshadcn.pages.dev}"
OUT="$HERE/wwwroot/sitemap.xml"

routes="$(find "$HERE/Pages" -name '*.razor' -print0 \
    | xargs -0 grep -h -m1 -oE '@page[[:space:]]+"[^"]+"' \
    | sed -E 's/.*"([^"]+)".*/\1/' \
    | grep -v -e '^/not-found$' -e '^/iframe/' -e '{' \
    | sort -u)"

{
    echo '<?xml version="1.0" encoding="UTF-8"?>'
    echo '<!-- Generated by generate-sitemap.sh. Do not edit by hand. -->'
    echo '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'
    # The home page and the guides first, then every component page.
    { echo "$routes" | grep -v '^/components/'; echo "$routes" | grep '^/components/'; } | while read -r route; do
        echo "  <url><loc>${SITE_URL}${route}</loc></url>"
    done
    echo '</urlset>'
} > "$OUT"

echo "Wrote $(grep -c '<loc>' "$OUT") URLs to ${OUT#"$HERE"/}"
